import React from "react";
import { FaSearch, FaShieldAlt, FaBolt, FaThumbsUp } from "react-icons/fa";

const FeaturesSection = () => {
  return (
    <section className="bg-white py-48 px-6 lg:px-32">
      <div className="text-center mb-16">
        <h2 className="text-7xl font-extrabold text-gray-900">
          Dive into AI-powered image analysis
        </h2>
        <p className="text-2xl text-gray-700 mt-8 max-w-4xl mx-auto">
          With <span className="text-blue-600 font-semibold">AI Image Detector</span>, you can effortlessly identify AI-generated images  
          without needing any technical skills.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-20 max-w-screen-lg mx-auto mt-20">
        

        <div className="flex items-start space-x-6">
          <div className="bg-blue-600 p-7 rounded-xl text-white text-6xl">
            <FaSearch />
          </div>
          <div>
            <h3 className="text-4xl font-bold text-gray-900">Image Authenticity Detection</h3>
            <p className="text-2xl text-gray-700 mt-2">
              Upload your images to determine if they were generated by AI or created by humans.
            </p>
          </div>
        </div>


        <div className="flex items-start space-x-6">
          <div className="bg-purple-600 p-7 rounded-xl text-white text-5xl">
            <FaShieldAlt />
          </div>
          <div>
            <h3 className="text-4xl font-bold text-gray-900">Verify Your Images</h3>
            <p className="text-2xl text-gray-700 mt-2">
              Leverages advanced AI models to assess images, providing insights into patterns and textures.
            </p>
          </div>
        </div>

  
        <div className="flex items-start space-x-6">
          <div className="bg-yellow-500 p-7 rounded-xl text-white text-5xl">
            <FaBolt />
          </div>
          <div>
            <h3 className="text-4xl font-bold text-gray-900">Quick Detection</h3>
            <p className="text-2xl text-gray-700 mt-2">
              Analyze images swiftly and receive immediate feedback on their authenticity.
            </p>
          </div>
        </div>


        <div className="flex items-start space-x-6">
          <div className="bg-green-500 p-7 rounded-xl text-white text-5xl">
            <FaThumbsUp />
          </div>
          <div>
            <h3 className="text-4xl font-bold text-gray-900">User-Friendly Interface</h3>
            <p className="text-2xl text-gray-700 mt-2">
              Our intuitive design makes it easy to upload and analyze images effortlessly.
            </p>
          </div>
        </div>

      </div>
    </section>
  );
};

export default FeaturesSection;
